### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#20]
# Todo

Please check the following link before proceeding to the migration: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate

When you pick a module, input your github id and the PR number after the name of the module:
- [X] business_requirement @sudhir-serpentcs #25 
- [ ] business_requirement_crm
- [X] business_requirement_deliverable @sudhir-serpentcs #26 
- [X] business_requirement_deliverable_categ @sudhir-serpentcs #29 
- [X] business_requirement_deliverable_cost @sudhir-serpentcs #30 
- [ ] business_requirement_deliverable_default
- [X] business_requirement_deliverable_report @sudhir-serpentcs #31 
- [ ] business_requirement_project

**Comment by elicoidal** [comment]
#133

**Comment by elicoidal** [comment]
Branch has been dropped following #133 
New branch has been initialized with the newest version of the v8 modules.
