### ISSUE TITLE
Migration to version 9.0 [CANCELED]

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#222]
# Todo

Please check the following link before proceeding to the migration: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate

When you pick a module, input your github id and the PR number after the name of the module:
- [ ] business_requirement
- [ ] business_requirement_deliverable
- [ ] business_requirement_deliverable_cost
- [ ] business_requirement_deliverable_crm
- [ ] business_requirement_deliverable_project
- [ ] business_requirement_deliverable_project_task_categ
- [ ] business_requirement_deliverable_report (TO BE MOVED TO EACH SPECIFIC MODULE)
- [ ] business_requirement_deliverable_resource_template
- [ ] business_requirement_deliverable_resource_template_categ
- [ ] business_requirement_earned_value
- [ ] business_requirement_etherpad

**Comment by elicoidal** [comment]
This request has not attracted interest so I will close it. It is unlikely that we will start a migration to v9, now that v11 is around the corner
