### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/business-requirement#260]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] business_requirement - By @victormmtorres - #309 
- [x] business_requirement_deliverable - By @victormmtorres - #311 
- [ ] business_requirement_deliverable_cost
- [ ] business_requirement_deliverable_crm
- [ ] business_requirement_deliverable_project
- [ ] business_requirement_deliverable_project_categ
- [ ] business_requirement_deliverable_project_task_categ
- [ ] business_requirement_deliverable_resource_template
- [ ] business_requirement_deliverable_resource_template_categ
- [ ] business_requirement_earned_value
- [ ] business_requirement_etherpad

**Comment by emagdalenaC2i** [comment]
seems that the master branch is 10.0, is it ok?

**Comment by elicoidal** [comment]
@emagdalenaC2i yes I set it to 10.0 as this is the main active code today. Migration to v11 has not yet started and when we have a decent volume of code we will switch to v11

**Comment by elicoidal** [comment]
Migration to v12 is ongoing.
No migration to v11 planned.
If anybody interested, please reopen the issue

**Comment by pedrobaeza** [comment]
Reopening as we are going to use this and refactor a bit. Only FYI.

**Comment by pedrobaeza** [comment]
Closing as this has been revamped with new specifications and it's completed.
