### ISSUE TITLE
Migration to version 10.0 [FINISHED]

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/business-requirement#48]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
When you pick a module, input your github id and the PR number after the name of the module:
- [x] business_requirement #223 
- [x] business_requirement_deliverable #224 
- [X] business_requirement_deliverable_categ (DEPRECATED)
- [x] business_requirement_deliverable_cost #225 
- [x] business_requirement_deliverable_crm #229 
- [x] business_requirement_deliverable_default (DEPRECATED)
- [x] business_requirement_deliverable_project #231 
- [X] business_requirement_deliverable_project_categ (DEPRECATED)
- [x] business_requirement_deliverable_project_task_categ #233 
- [x] business_requirement_deliverable_report (TO BE MOVED TO EACH SPECIFIC MODULE)
- [x] business_requirement_deliverable_resource_template #236 
- [x] business_requirement_deliverable_resource_template_categ #237
- [x] business_requirement_earned_value #234 (DEPRECATED)
- [x] business_requirement_etherpad #235

**Comment by elicoidal** [comment]
All good!. Migration Finished

**Comment by pedrobaeza** [comment]
Congratulations!
